// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dhuwpkwppzilapotvvkf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRodXdwa3dwcHppbGFwb3R2dmtmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA0Mjc0MzMsImV4cCI6MjA1NjAwMzQzM30.BuBHlIfNnqUma4hPkt8qwH8m8zNI0tEWHKj8DoF9MZE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);